---
- hosts: tvt4124
  collections:
    - ibm.ibm_zos_core
  gather_facts: no
  vars:
    tgt_tmp_dir: "/tmp"
    ctl_tmp_dir: "/tmp"
    dc_branch: "develop"
    dc_install_dir: "{{ dc_build_dir }}/{{ dc_branch }}"
  environment: "{{ environment_vars }}"

  tasks:
    # ##########################################################################
    # Fact setting for use by this playbook
    # ##########################################################################
    - name: Detecting system name
      #shell: "uname -a |awk '{print $2}'"
      command: uname -n
      register: result

    - name: Setting fact `system_name` for use by this sample
      set_fact:
        system_name: "{{ result.stdout }}"

    - name: Fact `system_name` set with value
      debug:
        msg: "{{ system_name }}"

    - name: Uncompress the data collector package
      shell: cd {{ dc_install_dir }}/DC; pax -ppx -rvzf CDP_dataservice.pax.z
      register: result

    - name: Response for generating the configuration file
      debug:
        msg: "{{ result }}"

    - name: List the files information of new build
      shell: ls -ltr {{ dc_install_dir }}/DC/*/*
      register: result

    - name: Response for generating the configuration file
      debug:
        msg: "{{ result }}"
